name: Publish Pipeline

on:
  workflow_dispatch: # Allows manual triggering
  release:
    types: [published]

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    environment: production # Requires environment approval for production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm run test:run
      
      - name: Build project
        run: npm run build
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish success notification
        run: echo "✅ Package published to NPM successfully"

  publish-github:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Configure package for GitHub Packages
        run: |
          cp package.json package.json.backup
          node -e "
            const pkg = require('./package.json');
            pkg.name = '@${{ github.repository_owner }}/' + pkg.name.split('/').pop();
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "
      
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Restore original package.json
        run: mv package.json.backup package.json
        if: always()
      
      - name: GitHub Packages success notification
        run: echo "✅ Package published to GitHub Packages successfully"