name: Publish Pipeline

on:
  workflow_dispatch: # Allows manual triggering
    inputs:
      use_artifact:
        description: 'Use build artifact (provide artifact name or "latest")'
        required: false
        default: ''
  release:
    types: [published]

jobs:
  build:
    name: Build for Publishing
    uses: ./.github/workflows/build.yml
    if: ${{ github.event.inputs.use_artifact == '' }}

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ always() && (needs.build.result == 'success' || github.event.inputs.use_artifact != '') }}
    environment: production # Requires environment approval for production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Download build artifacts (from current run)
        if: ${{ github.event.inputs.use_artifact == '' }}
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: ./
      
      - name: Download build artifacts (from specific run)
        if: ${{ github.event.inputs.use_artifact != '' && github.event.inputs.use_artifact != 'latest' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.use_artifact }}
          path: ./
      
      - name: Download latest build artifacts
        if: ${{ github.event.inputs.use_artifact == 'latest' }}
        run: |
          echo "Downloading latest build artifacts..."
          gh run download --name "build-artifacts-*" --limit 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install dependencies (only for package.json)
        run: npm ci --production
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish success notification
        run: echo "✅ Package published to NPM successfully"

  publish-github:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: [build, publish]
    if: ${{ always() && needs.publish.result == 'success' }}
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
      
      - name: Download build artifacts (reuse from publish job)
        if: ${{ github.event.inputs.use_artifact == '' }}
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: ./
      
      - name: Download build artifacts (from specific run)
        if: ${{ github.event.inputs.use_artifact != '' && github.event.inputs.use_artifact != 'latest' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.use_artifact }}
          path: ./
      
      - name: Download latest build artifacts
        if: ${{ github.event.inputs.use_artifact == 'latest' }}
        run: |
          echo "Downloading latest build artifacts..."
          gh run download --name "build-artifacts-*" --limit 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install dependencies (only for package.json)
        run: npm ci --production
      
      - name: Configure package for GitHub Packages
        run: |
          cp package.json package.json.backup
          node -e "
            const pkg = require('./package.json');
            pkg.name = '@${{ github.repository_owner }}/' + pkg.name.split('/').pop();
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "
      
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Restore original package.json
        run: mv package.json.backup package.json
        if: always()
      
      - name: GitHub Packages success notification
        run: echo "✅ Package published to GitHub Packages successfully"